server:
  port: ":8081"
postgresql:
  debugMode: true
  database: "wms"
  maxOpenConns: 10
  maxIdleConns: 2
  master:
    host: "localhost"
    port: "5432"
    username: "postgres"
    password: "1234"
  slaves:
    hosts: "localhost"
    port: "5432"
    username: "postgres"
    password: "1234"